#!/usr/bin/bash

set -e

trap clean 0 1 2 3 6

clean() {
  rm -f {Lex,Parse}.hs *.{hi,o} test tt
}

alex Lex.x
happy Parse.y

ghc -Wall -Werror -Wno-name-shadowing Main.hs -o tt

test() {
  ghc -Wall -Werror -Wno-name-shadowing -main-is Test.main Test.hs -o test

  ./test
  ./tt <input.txt |cmp output.txt
}

case "$1" in
  Main.hs) rlwrap ./tt;;
  *.hs)    ghci "$1";;
  test)    test;;
  *)       rlwrap ./tt;;
esac
